fee:
  # percentage of fees to be redistributed
  percentage: 0.5

redistribution:
  # type of redistribution (linear, weight-based)
  type: 'linear'
  # minimum balance (in SAT) of users to receive redistribution
  # used to avoid null or very small amounts (probably, unused wallets)
  minimum: 10000
  # maximum balance (in SAT) of users to receive redistribution
  # used to avoid very large amounts (probably, whales)
  # 2100000000000000 = maximum (21,000,000 BTC, max supply)
  maximum: 100000000