redistribution:
  # type of redistribution
  # [no_redistribution, equal, weight_based]
  # setting it to no_redistribution will invalidate all other parameters, although the computation time and performance will be affected
  type: 'weight_based'
  # percentage of amount to be redistributed
  percentage: 0.5
  # amount to redistribute
  # [fees, block_reward, total_reward]
  amount: 'total_reward'
  # minimum balance (in SAT) of users to receive redistribution
  # used to avoid null or very small amounts (probably, unused wallets)
  minimum: 10000
  # maximum balance (in SAT) of users to receive redistribution
  # used to avoid very large amounts (probably, whales)
  # 2100000000000000 = maximum (21,000,000 BTC, max supply)
  maximum: 100000000