addresses:
  # grouping addresses based on some heuristics
  # [single_input, multi_input]
  # single_input means that each address is treated as a separate account
  # multi_input is based on multi-input heuristics where all addresses that belong to the set of inputs of the same transaction are classified as a single entity
  grouping: 'single_input'

extra_fee:
  # extra fee amount in SATs
  # fee applied to the outputs of each transaction (except for the coinbase transaction)
  # set it to 0 for no extra fee
  amount_per_transaction: 0
  # extra fee amount in percentage
  # fee applied to the outputs of each transaction (except for the coinbase transaction)
  # set it to 0.0 for no extra fee
  percentage_per_transaction: 0.001

redistribution:
  # type of redistribution
  # [no_redistribution, equal, almost_equal, weight_based]
  # setting it to no_redistribution will invalidate all other parameters, although the computation time and performance will be affected
  type: 'weight_based'

  from:
    # percentage of amount to be redistributed
    percentage: 0.6
    # amount to redistribute
    # [fees, block_reward, total_reward]
    amount: 'fees'
  
  to:
    # minimum balance (in SAT) of users to receive redistribution
    # used to avoid null or very small amounts (probably, unused wallets)
    minimum: 100000
    # maximum balance (in SAT) of users to receive redistribution
    # used to avoid very large amounts (probably, whales)
    # 2100000000000000 = maximum (21,000,000 BTC, max supply)
    maximum: 10000000
    # percentage of eligible users that is going to receive the redistribution
    # example: 0.8 = only the 80% of poorest users (among the eligible ones) will receive the redistribution
    percentage: 1.0